//! Pure game rules. Must not depend on macroquad.
pub mod ai;
pub mod battle;
pub mod clock;
pub mod content;
pub mod events;
pub mod fog;
pub mod formation;
pub mod game;
pub mod items;
pub mod magic;
pub mod map;
pub mod rng;
pub mod save;
pub mod script;
pub mod ships;
pub mod town;
pub mod units;
pub mod world;
