[package]
name = "razdor"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.6.1"
dirs = "7.0.0"
encoding_rs = "0.8.42"
macroquad = "0.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["float_roundtrip"] }

[profile.dev.package."*"]
opt-level = 2
